{
 "title": "HomePower",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "influxdb" },
   { "name": "bucket", "label": "Bucket", "query": "buckets()" },
   {
    "name": "esp",
    "label": "ESP",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"${bucket}\")"
   },
   {
    "name": "solar",
    "label": "Solar",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"${bucket}\")"
   },
   {
    "name": "sol1",
    "label": "Sol 1",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementTagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"Phase\",\r\n  measurement: \"${solar}\"\r\n)"
   },
   {
    "name": "sol2",
    "label": "Sol 2",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementTagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"Phase\",\r\n  measurement: \"${solar}\"\r\n)"
   },
   {
    "name": "sol3",
    "label": "Sol 3",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementTagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"Phase\",\r\n  measurement: \"${solar}\"\r\n)"
   },
   {
    "name": "box",
    "label": "Box",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"${bucket}\")"
   },
   {
    "name": "box1",
    "label": "Box 1",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementTagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"Phase\",\r\n  measurement: \"${box}\"\r\n)"
   },
   {
    "name": "box2",
    "label": "Box 2",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementTagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"Phase\",\r\n  measurement: \"${box}\"\r\n)"
   },
   {
    "name": "box3",
    "label": "Box 3",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementTagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"Phase\",\r\n  measurement: \"${box}\"\r\n)"
   },
   { "name": "cost", "label": "Cost", "query": "0.1982" }
  ]
 },
 "panels": [
  {
   "title": "Self Production Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expression": "$LojaPower - $LojaSolar", "type": "math" },
    { "expression": "$CozinhaPower - $CozinhaSolar", "type": "math" },
    { "expression": "$CasaPower - $CasaSolar", "type": "math" }
   ]
  },
  { "title": "OverView", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "S Voltage Loja",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"voltage\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "S Current Loja",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"current\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "S Power Factor Loja",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"power-factor\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "power-factor" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "S Power Loja",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"power\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "S Energy Loja",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "S Frequency Loja",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"freq\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "freq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "Loja Saved 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 1d)\r\n  |> spread()\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value * 0.1982 }) )\r\n  |> yield()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*0.1982" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "Loja  Saved 7 Days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "7d" ], "type": "time" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 7d)\r\n  |> spread()\r\n  |> group(columns: [\"_measurement\"], mode:\"by\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value * 0.1982 }) )\r\n  |> yield()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*0.1982" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "Loja Saved 28 Days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -1mo)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 28d)\r\n  |> spread()\r\n  |> group(columns: [\"_measurement\"], mode:\"by\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value * 0.1982 }) )\r\n  |> yield()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*0.1982" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "Loja Saved Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value * 0.1982 }) )\r\n  |> yield()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*0.1982" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "S Current Combined",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\n  |> range(start: -10s)\n  |> filter(fn: (r) => r._measurement == \"Solar\")\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\n  |> filter(fn: (r) => r._field == \"current\")\n  |> last()\n  |> group(columns: [\"_field\"], mode:\"by\")\n  |> sum()",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "WiFi RSSI",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"${esp}\")\r\n  |> filter(fn: (r) => r.Device == \"${box}\" or r.Device == \"${solar}\")\r\n  |> filter(fn: (r) => r._field == \"wifi-rssi\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "wifi-rssi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32" }
     ]
    }
   ]
  },
  {
   "title": "S Voltage Cozinha",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"voltage\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-SolarCozinha" }
     ]
    }
   ]
  },
  {
   "title": "S Current Cozinha",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"current\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-SolarCozinha" }
     ]
    }
   ]
  },
  {
   "title": "S Power Factor Cozinha",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"power-factor\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "power-factor" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-SolarCozinha" }
     ]
    }
   ]
  },
  {
   "title": "S Power Cozinha",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"power\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-SolarCozinha" }
     ]
    }
   ]
  },
  {
   "title": "S Energy Cozinha",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-SolarCozinha" }
     ]
    }
   ]
  },
  {
   "title": "S Frequency Cozinha",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"freq\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "freq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-SolarCozinha" }
     ]
    }
   ]
  },
  {
   "title": "Cozinha Saved 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 1d)\r\n  |> spread()\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value * 0.1982 }) )\r\n  |> yield()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*0.1982" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "Cozinha  Saved 7 Days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "7d" ], "type": "time" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 7d)\r\n  |> spread()\r\n  |> group(columns: [\"_measurement\"], mode:\"by\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value * 0.1982 }) )\r\n  |> yield()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*0.1982" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "Cozinha Saved 28 Days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -1mo)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 28d)\r\n  |> spread()\r\n  |> group(columns: [\"_measurement\"], mode:\"by\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value * 0.1982 }) )\r\n  |> yield()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*0.1982" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "Cozinha Saved Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value * 0.1982 }) )\r\n  |> yield()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*0.1982" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-SolarCozinha" }
     ]
    }
   ]
  },
  {
   "title": "S Power Combined",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\n  |> range(start: -10s)\n  |> filter(fn: (r) => r._measurement == \"Solar\")\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\n  |> filter(fn: (r) => r._field == \"power\")\n  |> last()\n  |> group(columns: [\"_field\"], mode:\"by\")\n  |> sum()",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "S Voltage Casa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"voltage\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-SolarCozinha" }
     ]
    }
   ]
  },
  {
   "title": "S Current Casa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"current\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-SolarCozinha" }
     ]
    }
   ]
  },
  {
   "title": "S Power Factor Casa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"power-factor\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "power-factor" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-SolarCozinha" }
     ]
    }
   ]
  },
  {
   "title": "S Power Casa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"power\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-SolarCozinha" }
     ]
    }
   ]
  },
  {
   "title": "S Energy Casa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-SolarCozinha" }
     ]
    }
   ]
  },
  {
   "title": "S Frequency Casa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"freq\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "freq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-SolarCozinha" }
     ]
    }
   ]
  },
  {
   "title": "Casa Saved 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 1d)\r\n  |> spread()\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value * 0.1982 }) )\r\n  |> yield()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*0.1982" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "Casa  Saved 7 Days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "7d" ], "type": "time" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 7d)\r\n  |> spread()\r\n  |> group(columns: [\"_measurement\"], mode:\"by\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value * 0.1982 }) )\r\n  |> yield()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*0.1982" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "Casa Saved 28 Days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -1mo)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 28d)\r\n  |> spread()\r\n  |> group(columns: [\"_measurement\"], mode:\"by\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value * 0.1982 }) )\r\n  |> yield()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*0.1982" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "Casa Saved Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value * 0.1982 }) )\r\n  |> yield()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*0.1982" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-SolarCozinha" }
     ]
    }
   ]
  },
  {
   "title": "S Energy Combined",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\n  |> range(start: -10s)\n  |> filter(fn: (r) => r._measurement == \"Solar\")\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\n  |> filter(fn: (r) => r._field == \"energy\")\n  |> last()\n  |> group(columns: [\"_field\"], mode:\"by\")\n  |> sum()",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    }
   ]
  },
  {
   "title": "Solar vs Loja",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-Solar" }
     ]
    },
    {
     "alias": "Loja",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_2" }
     ]
    },
    { "expression": "$Loja - $Solar", "type": "math" }
   ]
  },
  {
   "title": "Solar vs Cozinha",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-SolarCozinha" }
     ]
    },
    {
     "alias": "Cozinha",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_1" }
     ]
    },
    { "expression": "$Cozinha - $Solar", "type": "math" }
   ]
  },
  {
   "title": "Solar vs Casa",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32-SolarCozinha" }
     ]
    },
    {
     "alias": "Casa",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_3" }
     ]
    },
    { "expression": "$Casa - $Solar", "type": "math" }
   ]
  },
  {
   "title": "Voltage Loja",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"voltage\")\r\n  |> last()\r\n  |> yield()",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_2" }
     ]
    }
   ]
  },
  {
   "title": "Current Loja",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"current\")\r\n  |> last()\r\n  |> yield()",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_2" }
     ]
    }
   ]
  },
  {
   "title": "Power Factor Loja",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"power-factor\")\r\n  |> last()\r\n  |> yield()",
     "select": [
      [
       { "params": [ "power-factor" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_2" }
     ]
    }
   ]
  },
  {
   "title": "Power Loja",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"power\")\r\n  |> last()\r\n  |> yield()",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_2" }
     ]
    }
   ]
  },
  {
   "title": "Energy Loja",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> last()\r\n  |> yield()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_2" }
     ]
    }
   ]
  },
  {
   "title": "Frequency Loja",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"freq\")\r\n  |> last()\r\n  |> yield()",
     "select": [
      [
       { "params": [ "freq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_2" }
     ]
    }
   ]
  },
  {
   "title": "Current Combinado",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\n  |> range(start: -10s)\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\n  |> filter(fn: (r) => r._field == \"current\")\n  |> last()\n  |> group(columns: [\"_field\"], mode:\"by\")\n  |> sum()",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_1" }
     ]
    }
   ]
  },
  {
   "title": "Energy Day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\n  |> range(start: today())\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\n  |> filter(fn: (r) => r._field == \"energy\")\n  |> window(every: 1d)\n  |> spread()\n  |> last()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> window(every: inf)\n  |> group(columns: [\"_field\"], mode:\"by\")\n  |> sum()\n  |> yield()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_1" }
     ]
    }
   ]
  },
  {
   "title": "Acq Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ESP32\")\r\n  |> filter(fn: (r) => r.Device == \"PowerBox\" or r.Device == \"Solar\")\r\n  |> filter(fn: (r) => r._field == \"acq-time\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()",
     "select": [
      [
       { "params": [ "wifi-rssi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32" }
     ]
    }
   ]
  },
  {
   "title": "Voltage Cozinha",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"voltage\")\r\n  |> last()\r\n  |> yield()",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_1" }
     ]
    }
   ]
  },
  {
   "title": "Current Cozinha",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"current\")\r\n  |> last()\r\n  |> yield()",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_1" }
     ]
    }
   ]
  },
  {
   "title": "Power Factor Cozinha",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"power-factor\")\r\n  |> last()\r\n  |> yield()",
     "select": [
      [
       { "params": [ "power-factor" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_1" }
     ]
    }
   ]
  },
  {
   "title": "Power Cozinha",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"power\")\r\n  |> last()\r\n  |> yield()",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_1" }
     ]
    }
   ]
  },
  {
   "title": "Energy Cozinha",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_1" }
     ]
    }
   ]
  },
  {
   "title": "Frequency Cozinha",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"freq\")\r\n  |> last()\r\n  |> yield()",
     "select": [
      [
       { "params": [ "freq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_1" }
     ]
    }
   ]
  },
  {
   "title": "Power Combinado",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\n  |> range(start: -10s)\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\n  |> filter(fn: (r) => r._field == \"power\")\n  |> last()\n  |> group(columns: [\"_field\"], mode:\"by\")\n  |> sum()",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_1" }
     ]
    }
   ]
  },
  {
   "title": "Energy Week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\n  |> range(start: -1w)\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\n  |> filter(fn: (r) => r._field == \"energy\")\n  |> window(every: 1w)\n  |> spread()\n  |> last()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> window(every: inf)\n  |> group(columns: [\"_field\"], mode:\"by\")\n  |> sum()\n  |> yield()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_1" }
     ]
    }
   ]
  },
  {
   "title": "Voltage Casa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"voltage\")\r\n  |> last()\r\n  |> yield()",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_3" }
     ]
    }
   ]
  },
  {
   "title": "Current Casa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"current\")\r\n  |> last()\r\n  |> yield()",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_3" }
     ]
    }
   ]
  },
  {
   "title": "Power Factor Casa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"power-factor\")\r\n  |> last()\r\n  |> yield()",
     "select": [
      [
       { "params": [ "power-factor" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_3" }
     ]
    }
   ]
  },
  {
   "title": "Power Casa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"power\")\r\n  |> last()\r\n  |> yield()",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_3" }
     ]
    }
   ]
  },
  {
   "title": "Energy Casa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> last()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_3" }
     ]
    }
   ]
  },
  {
   "title": "Frequency Casa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"freq\")\r\n  |> last()\r\n  |> yield()",
     "select": [
      [
       { "params": [ "freq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_3" }
     ]
    }
   ]
  },
  {
   "title": "Energy Combinado",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\n  |> range(start: -10s)\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\n  |> filter(fn: (r) => r._field == \"energy\")\n  |> last()\n  |> group(columns: [\"_field\"], mode:\"by\")\n  |> sum()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_1" }
     ]
    }
   ]
  },
  {
   "title": "Energy Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PowerBox",
     "query": "from(bucket: \"HomePower\")\n  |> range(start: -1mo)\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\n  |> filter(fn: (r) => r._field == \"energy\")\n  |> window(every: 1mo)\n  |> spread()\n  |> last()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> window(every: inf)\n  |> group(columns: [\"_field\"], mode:\"by\")\n  |> sum()\n  |> yield()",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Power_Phase", "operator": "=", "value": "Phase_1" }
     ]
    }
   ]
  },
  {
   "title": "Last PowerBox TS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ESP32\")\r\n  |> filter(fn: (r) => r[\"Device\"] == \"PowerBox\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"acq-time\")\r\n  |> keep(columns: [\"_time\", \"Device\"])\r\n  |> last(column: \"_time\")\r\n  |> yield()",
     "select": [
      [
       { "params": [ "wifi-rssi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32" }
     ]
    }
   ]
  },
  {
   "title": "Last Solar TS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar_1",
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -10s, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ESP32\")\r\n  |> filter(fn: (r) => r[\"Device\"] == \"Solar\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"acq-time\")\r\n  |> keep(columns: [\"_time\", \"Device\"])\r\n  |> last(column: \"_time\")\r\n  |> yield()",
     "select": [
      [
       { "params": [ "wifi-rssi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP32" }
     ]
    }
   ]
  },
  {
   "title": "Solar",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"voltage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()"
      }
     ]
    },
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"current\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()"
      }
     ]
    },
    {
     "title": "Power",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()"
      }
     ]
    },
    {
     "title": "Energy",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> aggregateWindow(every: 30m, fn: last, createEmpty: false)\r\n  |> difference()\r\n  |> yield()"
      }
     ]
    },
    {
     "title": "Power Factor",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"power-factor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()"
      }
     ]
    },
    {
     "title": "Frequency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"freq\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()"
      }
     ]
    },
    {
     "title": "Energy History Loja",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -3mo, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 1w, offset: 4d)\r\n  |> spread()\r\n  |> duplicate(column: \"_stop\", as: \"_time\")\r\n  |> group(columns: [\"host\", \"Phase\"], mode:\"by\")\r\n  |> yield()"
      },
      {
       "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -3mo, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 1d)\r\n  |> spread()\r\n  |> duplicate(column: \"_stop\", as: \"_time\")\r\n  |> group(columns: [\"host\", \"Phase\"], mode:\"by\")\r\n  |> yield()"
      }
     ]
    },
    {
     "title": "Energy History Cozinha",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -3mo, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 1w, offset: 4d)\r\n  |> spread()\r\n  |> duplicate(column: \"_stop\", as: \"_time\")\r\n  |> group(columns: [\"host\", \"Phase\"], mode:\"by\")\r\n  |> yield()"
      },
      {
       "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -3mo, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 1d)\r\n  |> spread()\r\n  |> duplicate(column: \"_stop\", as: \"_time\")\r\n  |> group(columns: [\"host\", \"Phase\"], mode:\"by\")\r\n  |> yield()"
      }
     ]
    },
    {
     "title": "Energy History Casa",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -3mo, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 1w, offset: 4d)\r\n  |> spread()\r\n  |> duplicate(column: \"_stop\", as: \"_time\")\r\n  |> group(columns: [\"host\", \"Phase\"], mode:\"by\")\r\n  |> yield()"
      },
      {
       "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -3mo, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"Solar\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 1d)\r\n  |> spread()\r\n  |> duplicate(column: \"_stop\", as: \"_time\")\r\n  |> group(columns: [\"host\", \"Phase\"], mode:\"by\")\r\n  |> yield()"
      }
     ]
    },
    {
     "title": "Energy History Combined",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "alias": "Daily",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"HomePower\")\n  |> range(start: -3mo, stop: now())\n  |> filter(fn: (r) => r._measurement == \"Solar\")\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\n  |> filter(fn: (r) => r._field == \"energy\")\n  |> window(every: 1w, offset: 4d)\n  |> spread()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> group(columns: [\"host\", \"_time\"], mode:\"by\")\n  |> sum()\n  |> group(columns: [\"host\", \"result\"], mode:\"by\")\n  |> yield()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Weekly",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"HomePower\")\n  |> range(start: -3mo, stop: now())\n  |> filter(fn: (r) => r._measurement == \"Solar\")\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\n  |> filter(fn: (r) => r._field == \"energy\")\n  |> window(every: 1d)\n  |> spread()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> group(columns: [\"host\", \"_time\"], mode:\"by\")\n  |> sum()\n  |> group(columns: [\"host\", \"result\"], mode:\"by\")\n  |> yield()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Power Box", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"voltage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"current\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> aggregateWindow(every: 30m, fn: last, createEmpty: false)\r\n  |> difference()\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"power-factor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"freq\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Energy History Loja",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -3mo, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 1w, offset: 4d)\r\n  |> spread()\r\n  |> duplicate(column: \"_stop\", as: \"_time\")\r\n  |> group(columns: [\"host\", \"Phase\"], mode:\"by\")\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -3mo, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Loja\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 1d)\r\n  |> spread()\r\n  |> duplicate(column: \"_stop\", as: \"_time\")\r\n  |> group(columns: [\"host\", \"Phase\"], mode:\"by\")\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Energy History Cozinha",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -3mo, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 1w, offset: 4d)\r\n  |> spread()\r\n  |> duplicate(column: \"_stop\", as: \"_time\")\r\n  |> group(columns: [\"host\", \"Phase\"], mode:\"by\")\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -3mo, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Cozinha\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 1d)\r\n  |> spread()\r\n  |> duplicate(column: \"_stop\", as: \"_time\")\r\n  |> group(columns: [\"host\", \"Phase\"], mode:\"by\")\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Energy History Casa",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -3mo, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 1w, offset: 4d)\r\n  |> spread()\r\n  |> duplicate(column: \"_stop\", as: \"_time\")\r\n  |> group(columns: [\"host\", \"Phase\"], mode:\"by\")\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"HomePower\")\r\n  |> range(start: -3mo, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\r\n  |> filter(fn: (r) => r.Phase == \"Casa\")\r\n  |> filter(fn: (r) => r._field == \"energy\")\r\n  |> window(every: 1d)\r\n  |> spread()\r\n  |> duplicate(column: \"_stop\", as: \"_time\")\r\n  |> group(columns: [\"host\", \"Phase\"], mode:\"by\")\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Energy History Combined",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Daily",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"HomePower\")\n  |> range(start: -3mo, stop: now())\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\n  |> filter(fn: (r) => r._field == \"energy\")\n  |> window(every: 1w, offset: 4d)\n  |> spread()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> group(columns: [\"host\", \"_time\"], mode:\"by\")\n  |> sum()\n  |> group(columns: [\"host\", \"result\"], mode:\"by\")\n  |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Weekly",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"HomePower\")\n  |> range(start: -3mo, stop: now())\n  |> filter(fn: (r) => r._measurement == \"PowerBox\")\n  |> filter(fn: (r) => r.Phase == \"Loja\" or r.Phase == \"Cozinha\" or r.Phase == \"Casa\")\n  |> filter(fn: (r) => r._field == \"energy\")\n  |> window(every: 1d)\n  |> spread()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> group(columns: [\"host\", \"_time\"], mode:\"by\")\n  |> sum()\n  |> group(columns: [\"host\", \"result\"], mode:\"by\")\n  |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}